"""add llm response

Revision ID: 96fd37db807b
Revises: 2ca349fa0a47
Create Date: 2025-11-17 18:39:32.437782

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '96fd37db807b'
down_revision: str | Sequence[str] | None = '2ca349fa0a47'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_result',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('llmResponse', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_result_id'), 'llm_result', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_result_id'), table_name='llm_result')
    op.drop_table('llm_result')
    # ### end Alembic commands ###
